defaultContentLanguage = "en"
theme = "congo"
enableRobotsTXT = true
paginate = 5
rssLimit = 10
summaryLength = 0
metaDataFormat = "yaml"
disqusShortname = "realjenius"

[outputs]
home = ["HTML", "RSS", "JSON"]

[permalinks]
post = "/:year/:month/:day/:filename/"

[taxonomies]
tag = 'tags'
category = 'categories'
series = 'series'